// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjzzuzgjorkfwdjdstjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqenp1emdqb3JrZndkamRzdGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTUwMzgsImV4cCI6MjA2NzY3MTAzOH0.O7Wlun97oyfiGZ8pBbrUiI2fSofPpIlB1aEi_aLXsJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});