name: Auto Project Summary to Notion

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  summarize-and-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install openai requests

      - name: Save commit messages to file
        run: |
          git log -5 --pretty=format:"- %s" > commits.txt

      - name: Generate summary with GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 generate_summary.py > summary.txt

      - name: Append to PROJECT_LOG.md
        run: |
          echo "## $(date +'%Y-%m-%d')" >> PROJECT_LOG.md
          cat summary.txt >> PROJECT_LOG.md
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add PROJECT_LOG.md
          git commit -m "chore: update project log"
          git push

      - name: Push summary to Notion
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          python3 push_to_notion.py
